services:
  - type: web
    name: notely
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: APP_TITLE
        value: Notely
      - key: NOTES_FILE
        value: notes.json